package com.nationsbenefits.igloo.authengine.constant;
/**
 * @author PwC
 * Copyright Â© 2024, NationsBenefits. All Rights reserved
 * This is the Constant Class to store all event names  to use in ISO8583 adapter service
 */
public  interface EventConstant {

     public static final String ADJUDICATION_MESSAGE_RECEIVED = "ADJUDICATION_MESSAGE_RECEIVED";

    public static final String ADJUDICATION_CARD_DETAILS_VALIDATED = "ADJUDICATION_CARD_DETAILS_VALIDATED";
    public static final String ADJUDICATION_CARD_DETAILS_NOT_FOUND = "ADJUDICATION_CARD_DETAILS_NOT_FOUND";
    public static final String ADJUDICATION_MEMBER_DETAILS_VALIDATED = "ADJUDICATION_MEMBER_DETAILS_VALIDATED";
    public static final String ADJUDICATION_TRANSACTION_FRAUD_CHECK_SUCCESS = "ADJUDICATION_TRANSACTION_FRAUD_CHECK_SUCCESS";
    public static final String ADJUDICATION_MEMBER_ACCOUNT_DETAILS_VALIDATED = "ADJUDICATION_MEMBER_ACCOUNT_DETAILS_VALIDATED";
    public static final String ADJUDICATION_BAS_ADJUDICATION_SUCCESS= "ADJUDICATION_BAS_ADJUDICATION_SUCCESS";
    public static final String ADJUDICATION_SUCCESS_RESPONSE_CREATED= "ADJUDICATION_SUCCESS_RESPONSE_CREATED";
    public static final String ADJUDICATION_SUCCESS_RESPONSE_SENT= "ADJUDICATION_SUCCESS_RESPONSE_SENT";
    public static final String ADJUDICATION_LEDGER_POST_SUCCESS= "ADJUDICATION_LEDGER_POST_SUCCESS";
    public static final String ADJUDICATION_LEDGER_POST_FAILED= "ADJUDICATION_LEDGER_POST_FAILED";
    public static final String ADJUDICATION_BAS_ADJUDICATION_FAILED= "ADJUDICATION_BAS_ADJUDICATION_FAILED";
    public static final String ADJUDICATION_INTERRUPT_EXCEPTION_OCCURRED = "ADJUDICATION_INTERRUPT_EXCEPTION_OCCURRED";
    public static final String ADJUDICATION_SERVICE_EXECUTION_EXCEPTION_OCCURRED = "ADJUDICATION_SERVICE_EXECUTION_EXCEPTION_OCCURRED";

    public static final String ADJUDICATION_FRAUD_CHECK_FAILED = "ADJUDICATION_FRAUD_CHECK_FAILED";



    public static final String CANONICAL_MODEL_CREATED = "CANONICAL_MODEL_CREATED";

    public static final String CANONICAL_MODEL_CREATION_FAILED = "CANONICAL_MODEL_CREATION_FAILED";
    public static final String AUTHORIZATION_PROCESS_TRIGGERED = "AUTHORIZATION_PROCESS_TRIGGERED";

    public static final String AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";

    public static final String AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED";

    public static final String ISO8583_AUTH_SUCCESS_RESPONSE_CREATED = "ISO8583_AUTH_SUCCESS_RESPONSE_CREATED";

    public static final String ISO8583_AUTH_FAILURE_RESPONSE_CREATED = "ISO8583_AUTH_FAILURE_RESPONSE_CREATED";

    public static final String ISO8583_AUTH_RESPONSE_SEND = "ISO8583_AUTH_RESPONSE_SEND";
}

