apiVersion: v1
kind: Service
metadata:
  name: $SERVICENAME
spec:
  selector:
    app: $SERVICENAME
  #type: LoadBalancer  
  ports:
    # - protocol: TCP
    #   name: service
    #   port: 8081
    #   targetPort: 8081
    - protocol: TCP
      name: grpc
      port: 9091
      targetPort: 9091
    
