apiVersion: v1
kind: Service
metadata:
  name: $SERVICENAME
spec:
  selector:
    app: $SERVICENAME
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: service
